version: 2

jobs:
  build:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-mocha-chai-lib
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install package dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-mocha-chai-lib
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: yarn test

  release:
    docker:
      - image: circleci/node:6
    working_directory: ~/node-mocha-chai-lib
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Compile
          command: yarn build
      - run:
          name: Git release
          command: yarn release:git

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - master
